server {
    listen 8080;

    # Healthcheck requerido por Fury
    location = /ping {
        return 200 'pong';
        add_header Content-Type text/plain;
    }

    # Archivos estáticos del build de React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Soporte para React Router (client-side routing)
        try_files $uri $uri/ /index.html;
    }
}
